//
//  AlarmType+CoreDataProperties.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

// MARK: - AlarmType properties

extension AlarmType {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<AlarmType> {
        return NSFetchRequest<AlarmType>(entityName: "AlarmType")
    }

    @NSManaged public var name: String

    @NSManaged public var alarms: Set<Alarm>

}

// MARK: - AlarmType KVC compliant to-many accessors and helpers

extension AlarmType {

    @objc(addAlarmsObject:)
    @NSManaged public func addToAlarms(_ value: Alarm)

    @objc(removeAlarmsObject:)
    @NSManaged public func removeFromAlarms(_ value: Alarm)

    @objc(addAlarms:)
    @NSManaged public func addToAlarms(_ values: Set<Alarm>)

    @objc(removeAlarms:)
    @NSManaged public func removeFromAlarms(_ values: Set<Alarm>)

}

