//
//  Alarm+CoreDataProperties.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

// MARK: - Alarm properties

extension Alarm {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Alarm> {
        return NSFetchRequest<Alarm>(entityName: "Alarm")
    }

    @NSManaged public var hour: Date
    @NSManaged public var label: String
    @NSManaged public var repeats: Bool
    @NSManaged public var repetitionFlag: Int64 // cannot mark as optional because Objective-C compatibility issues

    @NSManaged public var type: AlarmType

}

