//
//  Alarm+AlecrimCoreDataAttributes.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData


// MARK: - Alarm query attributes

extension Alarm {

    public static let hour = AlecrimCoreData.Attribute<Date>("hour")
    public static let label = AlecrimCoreData.Attribute<String>("label")
    public static let repeats = AlecrimCoreData.Attribute<Bool>("repeats")
    public static let repetitionFlag = AlecrimCoreData.NullableAttribute<Int64>("repetitionFlag")

    public static let type = AlecrimCoreData.Attribute<AlarmType>("type")

}

// MARK: - AttributeProtocol extensions

extension AlecrimCoreData.AttributeProtocol where Self.ValueType: Alarm {

    public var hour: AlecrimCoreData.Attribute<Date> { return AlecrimCoreData.Attribute<Date>("hour", self) }
    public var label: AlecrimCoreData.Attribute<String> { return AlecrimCoreData.Attribute<String>("label", self) }
    public var repeats: AlecrimCoreData.Attribute<Bool> { return AlecrimCoreData.Attribute<Bool>("repeats", self) }
    public var repetitionFlag: AlecrimCoreData.NullableAttribute<Int64> { return AlecrimCoreData.NullableAttribute<Int64>("repetitionFlag", self) }

    public var type: AlecrimCoreData.Attribute<AlarmType> { return AlecrimCoreData.Attribute<AlarmType>("type", self) }

}

// MARK: - NSManagedObjectContext extensions

extension NSManagedObjectContext {

    public var alarms: AlecrimCoreData.Table<Alarm> { return AlecrimCoreData.Table<Alarm>(context: self) }

}

